language: generic # travis-ci has outdated compilers :(
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev libsoil-dev libfreetype6-dev libbullet-dev libgl1-mesa-dev libglu1-mesa-dev libglm-dev
  - sudo pip install cpp-coveralls

install:
  - wget https://github.com/nigels-com/glew/releases/download/glew-2.0.0/glew-2.0.0.tgz
  - tar -xzvf glew-2.0.0.tgz
  - pushd glew-2.0.0 && make && sudo make install && popd
  - wget https://github.com/assimp/assimp/archive/v3.3.1.tar.gz
  - tar -xzvf v3.3.1.tar.gz
  - pushd assimp-3.3.1 && mkdir build && cd build && cmake .. && make -j4 && sudo make install && popd

script:
  - mkdir glfw_git
  - cd glfw_git
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -G "Unix Makefiles" .
  - make
  - sudo make install
  - pkg-config --libs glfw3
  - cat /usr/local/lib/pkgconfig/glfw3.pc
  - pkg-config --list-all | grep "glf"
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" -E ".*glfw_git.*" -E ".*glew-.*" -E ".*assimp-3.3.1.*"
