language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - openrave
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake
    - assimp
    - bullet
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev libsoil-dev libassimp-dev libfreetype6-dev libbullet-dev libgl1-mesa-dev libglew-dev libglm-dev
script:
  - mkdir glfw_git
  - cd glfw_git
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -G "Unix Makefiles" .
  - make
  - sudo make install
  - pkg-config --libs glfw3
  - cat /usr/local/lib/pkgconfig/glfw3.pc
  - pkg-config --list-all | grep "glf"
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake .. && make
