language: generic # travis-ci has outdated compilers :(
sudo: required
dist: trusty

# enable cache to allow faster installation of required packages
cache:
  directories:
    - scripts/build
addons:
  apt:
    packages:
      - g++-6
    sources:
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - llvm-toolchain-precise-3.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev libsoil-dev libfreetype6-dev libbullet-dev libgl1-mesa-dev libglu1-mesa-dev libglm-dev
  - sudo pip install cpp-coveralls

install:
  - scripts/install_glew.sh
  - scripts/install_assimp.sh
  - scripts/install_glfw.sh

script:
  - $CXX --version
  - mkdir -p build && cd build
  - cmake ..
  - make VERBOSE=1
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" -E ".*glfw_git.*" -E ".*glew-.*" -E ".*assimp-3.3.1.*"
