language: cpp
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev libsoil-dev libassimp-dev libfreetype6-dev libbullet-dev libgl1-mesa-dev libglm-dev
  - sudo pip install cpp-coveralls

install:
  - wget https://github.com/nigels-com/glew/releases/download/glew-2.0.0/glew-2.0.0.tgz
  - tar -xzvf glew-2.0.0.tgz
  - pushd glew-2.0.0 && make && sudo make install && popd

script:
  - mkdir glfw_git
  - cd glfw_git
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -G "Unix Makefiles" .
  - make
  - sudo make install
  - pkg-config --libs glfw3
  - cat /usr/local/lib/pkgconfig/glfw3.pc
  - pkg-config --list-all | grep "glf"
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"
